version: "3"

services:
  mc:
    container_name: mc
    image: itzg/minecraft-server:java17-jdk
    ports:
      - "25565:25565"
      - "3876:3876"
      - "24454:24454/udp"
    environment:
      DEBUG: "true"
      VERSION: "1.20.1"
      MEMORY: "10G"
      EULA: "TRUE"
      TYPE: "QUILT"
      OPS: "scotus1,8d8982a5-8cf9-4604-8feb-3dd5ee1f83a3"
      PACKWIZ_URL: "https://raw.githubusercontent.com/scotus-1/hotpot/main/pack.toml"
      # JVM_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseNUMA -XX:AllocatePrefetchStyle=3 -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:+EagerJVMCI -XX:+UseG1GC -XX:MaxGCPauseMillis=130 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=28 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=20 -XX:G1MixedGCCountTarget=3 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcMarkStepDurationMillis=5 -XX:G1ConcRSHotCardLimit=16 -XX:G1ConcRefinementServiceIntervalMillis=150 -Dgraal.TuneInlinerExploration=1 -Dgraal.CompilerConfiguration=enterprise"
      MOTD: "don cheadle"
      DIFFICULTY: "hard"
      ENFORCE_WHITELIST: true
      ENABLE_WHITELIST: true
      ICON: "./icon.png"
      MAX_PLAYERS: 16
      USE_AIKAR_FLAGS: true
      QUILT_LOADER_VERSION: 0.26.0
      SPAWN_PROTECTION: 0

    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./server:/data

    restarter:
      image: docker:cli
      restart: unless-stopped
      volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
      entrypoint: ["/bin/sh","-c"]
      command:
        - |
          while true; do
            if [ "$$(date +'%H:%M')" = '13:00' ]; then
                docker restart mc
                sleep 240
                docker exec -it mc rcon-cli chunky continue
            fi
            sleep 60
          done
