name = "hotpot"
author = "scotus*"
version = "v1.0.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6862a4f38fbf6aa67156f2cdbbd241b6dd8006b19e994da7e055bd491a0d9544"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
