name = "hotpot"
author = "scotus*"
version = "v1.0.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "faf21bdab6728af63ae7167d8cbecd4a2babae356d46401f6062b931eff07ca2"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
