name = "hotpot"
author = "scotus*"
version = "v1.0.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28d752ecd9282eeb9572c363a825b2b8ee33de5e879871589ceadcdd5e5bbc78"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
