name = "hotpot"
author = "scotus*"
version = "v1.0.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67d6780df08020577fcb0c5a8b00b38d8acf04c2ca115d5e0ff3483b0ce181b9"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
