name = "hotpot"
author = "scotus*"
version = "v1.0.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac2788a8deef0ce3644ab91342471b3e2caf42fd72e15182acf79f5b10c7ca71"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
