name = "hotpot"
author = "scotus*"
version = "v1.0.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48c58e81e5f56081a24a92011cb1436ed190e08fb2ce81cb5e4c5de2d12179d7"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0-beta.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
