name = "hotpot"
author = "scotus*"
version = "v1.0.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afa8fd9bef46fcf225fd8cfd22c7fb8b6a119a152ca4ab3ae0a8e7fe18319a33"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
