name = "hotpot"
author = "scotus*"
version = "v1.0.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62be312d4475a696978b73411231c9f1de47b164fe9d43c23c573079998b2a32"

[versions]
lwjgl3 = "3.3.1"
minecraft = "1.20.1"
quilt = "0.26.0"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
