name = "hotpot"
author = "scotus*"
version = "v1.0.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e2f67f989c4700301c64127371e6cc1a605f04ff4c606c88635b21b1fdb6b0e"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
